version: "1"
projects:
- name: My project
  environments:
  - name: Production
    databases:
    - name: airdrop-db
      databaseName: airdrop_db
      user: airdrop_db_user
      plan: free
      region: oregon
      postgresMajorVersion: "18"
